name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      
      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build

      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "gh-actions"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "futurology.css"
          target: "/tmp"
      
      - name: Run commands over SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: gh-actions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo cp -v /tmp/futurology.css /srv/lemmy/futurology.today/volumes/lemmy-ui/extra_themes/futurology.css